version: '3'
services:
  db:
    image: postgres:9.6-alpine
    volumes:
      - postgres-volume:/var/lib/postgresql/data
  redis:
    image: redis:4.0-alpine
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - 'redis:/data'
  sidekiq:
    depends_on:
      - db
      - redis
    build: .
    command: sidekiq -C config/sidekiq.yml.erb
    volumes:
      - .:/test-backend
  web:
    build: .
    command: rails s -b 0.0.0.0 -p 3000
    volumes:
      - .:/test-backend
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - sidekiq
    tty: true
    stdin_open: true

volumes:
  postgres-volume:
  redis:
